Feature/model creator
pylhc/omc3 pull request #286
Opened 2021-06-23 20:30 UTC by JoschD

Fixes #283 
Fixes #284 
Fixes #285 
Changes towards #238 for model creation and accelerator class

2021-06-23 21:06 UTC, fsoubelet commented on omc3/model/accelerators/accelerator.py
> +        modifiers = re.findall(fr"\s+call,\s*file\s*=\s*[\"\']?([^;\'\"]+)[\"\']?\s*;\s*{MODIFIER_TAG}", job_madx,
Could use a comment to explain that regex, so we don't need to think about it too much later on

2021-06-23 21:08 UTC, fsoubelet commented on omc3/model/accelerators/lhc.py
> +        LOG.info("Natural Tune X      [{:10.3f}]".format(self.nat_tunes[0]))
let's use f-strings everywhere here

2021-06-23 21:11 UTC, fsoubelet commented on omc3/model/accelerators/ps/base.mask
> -/************************************************************
Why are we getting rid of this block?

2021-06-23 21:11 UTC, fsoubelet commented on omc3/model/accelerators/ps/base.mask
> -/************************************************************
Nevermind I see it's moved in a different file.

2021-06-23 21:15 UTC, fsoubelet commented on omc3/model_creator.py
> +from omc3. utils import logging_tools
typo space in import

2021-06-23 21:15 UTC, fsoubelet commented on omc3/model_creator.py
> +        help="Type of model to create, either nominal or best_knowledge"
Help does not reflect choices

2021-06-23 21:17 UTC, fsoubelet commented on omc3/model_creator.py
> -    if sys.flags.debug:
Removing the option to enable debug logging? :(

2021-06-23 21:19 UTC, fsoubelet commented on omc3/model_creator.py
> -    if sys.flags.debug:
Nevermind again, I see the logic has been moved to logging_tools 👍

2021-06-24 12:28 UTC, fsoubelet requested changes
Just a small omission as I can tell, otherwise LGTM

2021-06-24 12:28 UTC, fsoubelet commented on tests/unit/test_model_creator.py
> +def test_lhc_creation_best_knowledge(tmp_path):
This test does not test the creation.

2021-06-24 12:58 UTC, JoschD commented on tests/unit/test_model_creator.py
> +def test_lhc_creation_best_knowledge(tmp_path):
Ooops. It did at some point

2021-06-24 15:41 UTC, tpersson approved these changes
I had a look and no comments on the changes but just observations that still are a lot of things missing such as a real creation of the segment-by-segment but that is fine and I will have a look at that shortly. I think it is crucial that this PR is merged so we can merge the correction branch.

2021-06-24 17:13 UTC, fsoubelet approved these changes

2021-06-24 17:28 UTC, merged