Fix for larger errorst in first/last bpms (thx Andreas)
pylhc/omc3 pull request #430
Opened 2023-10-16 13:03 UTC by fscarlier

Andreas remembered the quick fix for the large errors found in the first and last bpms for the 3-bpm method.

2023-10-16 13:08 UTC, awegsche submitted a review, later dismissed

2023-10-16 13:13 UTC, fsoubelet approved these changes

2023-10-16 13:29 UTC, JoschD requested changes
bumpversion to 0.11.4 and changelog

2023-10-16 14:06 UTC, JoschD commented
on a sidenote: Do I see this correctly, that the 3BPM-Method is not tested at all?

2023-10-17 09:39 UTC, fsoubelet approved these changes

2023-10-17 13:13 UTC, JoschD approved these changes

2023-10-20 07:11 UTC, merged