Update RDT tests
pylhc/omc3 pull request #478
Opened 2024-12-16 11:16 UTC by jgray-19

- Remove previous, unreproducible tests. 
- Add tests based on MAD-NG
- Includes test with analytical for sextupolar RDTs
- Includes files to reproduce test files.

Will remain a draft until this is merged: https://github.com/pylhc/turn_by_turn/pull/21

2025-01-09 12:06 UTC, fsoubelet reviewed
That's a lot of code, maybe we should write tests for our tests.

Main comments / concerns on top of the below:
- The use of hardcoded paths to your own `acc-models-lhc` files. A fixture was set up at some point to get `acc-models-lhc` for tests, maybe it'd be better to use this and assume the dir is present, instead of potentially making symlinks etc.
- I am concerned about the size. Asking the `gh` tool to checkout this PR got `git` downloading 299.42MiB of data! I don't see file sizes in the review interface so I can't confirm this but it feels worrying.

2025-01-09 12:06 UTC, fsoubelet commented on tests/inputs/lhc_rdts/create_data.py
> +    # Convert the MAD-NG output to a MAD-X style TFS (waiting for TFS update)
We have thge `tfs` update, is this still needed?

2025-01-09 12:06 UTC, fsoubelet commented on tests/inputs/lhc_rdts/create_data.py
> +# Convert a MAD-NG output into a fake measurement, then use OMC3 to calculate this fake measurement.
This is a very confusing sentence and does not look like this is what is being done in this file.

2025-01-10 09:04 UTC, jgray-19 commented
> That's a lot of code, maybe we should write tests for our tests.
> 
> Main comments / concerns on top of the below:
> 
>     * The use of hardcoded paths to your own `acc-models-lhc` files. A fixture was set up at some point to get `acc-models-lhc` for tests, maybe it'd be better to use this and assume the dir is present, instead of potentially making symlinks etc.
> 
>     * I am concerned about the size. Asking the `gh` tool to checkout this PR got `git` downloading 299.42MiB of data! I don't see file sizes in the review interface so I can't confirm this but it feels worrying.

Wow 300 MiB that's a lot - does git download previous commits, rather than just the latest? I would only expect ~30 MiB (from checking the size of the lhc_rdts folder). Also, I have not quite got used to not hardcoding the paths, so definitely something I will change.

2025-01-10 09:05 UTC, jgray-19 commented on tests/accuracy/test_lhc_rdts.py
> +    },
No, I lowered them as far as they would go in the test. A higher error for the octupoles is expected, not necessarily beam dependant. I was trying to set them to a value that catches any increase in error?

2025-01-10 09:07 UTC, jgray-19 commented on tests/accuracy/test_lhc_rdts.py
> +          dependent on a low kick amplitude to produce correct results.
Let me verify.

2025-01-10 09:16 UTC, jgray-19 commented on tests/accuracy/test_lhc_rdts.py
> +          dependent on a low kick amplitude to produce correct results.
Ok, looks like this bit is outdated. What seems to have happened was my skew sextupole strength was quite large, this resulted in some detuning, which appeared to reduce the error when the kick was lower. 

Conclusion: I need to rewrite the docstring.

2025-01-10 09:22 UTC, jgray-19 commented on tests/inputs/lhc_rdts/rdt_constants.py
> +# that are not on any of the tune lines, as these are 0 when calculated from OMC3.
I think it's something that physically cannot be measured from the frequency spectrum. If the RDT is only having an effect on the tune line, I'm not sure that it's amplitude or phase can be extracted, as it will just find the betatron phase and some combination of amplitudes? @JoschD have I understood correctly?

2025-01-10 09:23 UTC, jgray-19 commented on tests/inputs/lhc_rdts/rdt_constants.py
> +    os.system(f"ln -s /afs/cern.ch/eng/acc-models/lhc/2024/ {ACC_MODELS}")
Hmmm... This is only for someone running the tracking I think... I'll move it to the right file.

2025-01-10 09:24 UTC, jgray-19 commented on tests/inputs/lhc_rdts/omc3_helpers.py
> +    return df.filter(regex=r"^BPM\.[1-9][0-9].", axis="index")
Ahh sorry, should be `filter_out_BPMS_near_IPs`

2025-01-10 09:26 UTC, jgray-19 commented on tests/accuracy/test_lhc_rdts.py
> +    run_harpy(beam=2)
I've done a lot of tweaking. What were you thinking to do?

2025-01-10 09:28 UTC, jgray-19 commented on tests/inputs/lhc_rdts/omc3_helpers.py
> +    return tunes
Ooo that looks good, thanks for making me aware!

2025-01-10 09:31 UTC, jgray-19 commented on tests/inputs/lhc_rdts/omc3_helpers.py
> +    if not check_previous or any(not path.exists() for path in rdt_paths.values()):
I prefer `is False` I think, it's more explicit.

2025-01-10 09:32 UTC, jgray-19 commented on tests/inputs/lhc_rdts/omc3_helpers.py
> +        print(f"Tunes for beam {beam}: {tunes}")
I think only when there is an issue, but sure, I'll log

2025-01-10 09:36 UTC, jgray-19 commented on tests/inputs/lhc_rdts/model_b2/job.create_model_nominal.madx
> +}
Ahh damn. This is the automatic output of the model_creation, I think I could just delete this file?

2025-01-10 09:38 UTC, jgray-19 commented on tests/inputs/lhc_rdts/create_data.py
> +    model_ng = run_twiss_rdts(beam, ng_rdts)
One converts the rdts from the list of RDTs into the list that madng needs to understand what to calculate. The other calculates then for all the RDTs.

2025-01-10 09:39 UTC, jgray-19 commented on tests/accuracy/test_lhc_rdts.py
> +    ng_complex = ng_df[f"{ng_rdt}REAL"] + 1j * ng_df[f"{ng_rdt}IMAG"]
Oh yes, I can now, there's a lot actually that can be simplified. Let me work on that.

2025-01-10 09:46 UTC, jgray-19 commented on tests/inputs/lhc_rdts/model_b2/job.create_model_nominal.madx
> +}
Can you check the latest commit?

2025-01-10 09:48 UTC, jgray-19 commented on tests/inputs/lhc_rdts/MAD_helpers.py
> +from pymadng import MAD
Not exactly - perhaps another optional called like generate_tests, if you prefer.  But MAD_helpers.py is _only_ run when the data needs to be regenerated.

2025-01-10 09:48 UTC, jgray-19 commented on tests/inputs/lhc_rdts/MAD_helpers.py
> +                        )
Noted. I'll have a look

2025-01-10 09:53 UTC, jgray-19 commented on tests/inputs/lhc_rdts/create_data.py
> +    # Convert the MAD-NG output to a MAD-X style TFS (waiting for TFS update)
Nope. Working on it.

2025-01-10 09:53 UTC, jgray-19 commented on tests/inputs/lhc_rdts/create_data.py
> +# Convert a MAD-NG output into a fake measurement, then use OMC3 to calculate this fake measurement.
I'll rewrite

2025-01-10 10:30 UTC, fsoubelet commented on tests/accuracy/test_lhc_rdts.py
> +    },
K, no worries. Tolerances have to be somewhere anyway, just wondering how you got these.

2025-01-10 10:31 UTC, JoschD commented on tests/inputs/lhc_rdts/rdt_constants.py
> +# that are not on any of the tune lines, as these are 0 when calculated from OMC3.
I am not sure if I even understand the sentence. Are they actually 0 in OMC3? Or are they just avoided?
I think normally we assign the lines to RDTs which are contributing in first order to that line. So the tune lines are clearly driven by RDTs of order 0 (i.e. the tune)?

2025-01-10 10:32 UTC, fsoubelet commented on tests/inputs/lhc_rdts/omc3_helpers.py
> +    return f"tbt_data_{get_file_suffix(beam)}.{'sdds' if sdds else 'tfs.bz2'}"
Cool, no worries. Just regarding my main concern it seems like the repo it getting big, fast, so I wanted to make sure we compress well.

2025-01-10 10:33 UTC, jgray-19 commented on tests/inputs/lhc_rdts/rdt_constants.py
> +# that are not on any of the tune lines, as these are 0 when calculated from OMC3.
They are exactly 0, in the files that they produce. Not sure if this is because they are avoided

2025-01-10 10:35 UTC, fsoubelet commented on tests/inputs/lhc_rdts/create_data.py
> +    model_ng = run_twiss_rdts(beam, ng_rdts)
Yeah sorry, I realised that when looking at the helpers file later in my review. Maybe a quick comment could be useful but this is not crucial in any way. Feel free to resolve.

2025-01-10 10:35 UTC, fsoubelet commented on tests/accuracy/test_lhc_rdts.py
> +    ng_complex = ng_df[f"{ng_rdt}REAL"] + 1j * ng_df[f"{ng_rdt}IMAG"]
Come and live in the future my friend :D

2025-01-10 10:36 UTC, JoschD commented on tests/inputs/lhc_rdts/MAD_helpers.py
> +from pymadng import MAD
I would prefer a `requirements.txt` in the tests/inputs/lhc_rdts folder

2025-01-10 10:36 UTC, fsoubelet commented on tests/inputs/lhc_rdts/MAD_helpers.py
> +from pymadng import MAD
Ah yes I did not look carefully at the cycle of imports and calls, I assumed this file was imported too during tests. In this case I have no issue leaving it as is, let's not have extras for everything. Let's see if @JoschD is ok with that as well

2025-01-10 10:37 UTC, fsoubelet commented on tests/inputs/lhc_rdts/create_data.py
> +    # Convert the MAD-NG output to a MAD-X style TFS (waiting for TFS update)
Right, then no worries. Feel free to resolve.

2025-01-10 10:43 UTC, fsoubelet commented
Upon double checking, I have no idea what the hell the `gh` tool is doing when checking out a PR. Here's what I can confirm:
- git cloning the master branch (with `--depth=1`) -> 68.63 MiB downloaded.
- git cloning directly your branch (with `--depth=1`) -> 73.61 MiB downloaded.

My concern regarding this PR's file sizes is gone, since you're adding about 5MiB. Considering we are shipping 46M of binaries I guess there's only so much we can do. I dream of reworking things to use `cpymad` at some point, but never got around to it.

2025-01-10 10:45 UTC, fsoubelet commented on tests/inputs/lhc_rdts/model_b2/job.create_model_nominal.madx
> +}
If you mean b8ba603b7c1cbffcc5eb93334cfb6b67be91827a then I get your intent but it might be a bit rough too. Maybe at least let's add an `echo` line at the beginning of the script stating "If you encounter a crash in this script make sure you have ran ...". Curious about @JoschD's take on this

2025-01-10 10:54 UTC, jgray-19 commented on tests/accuracy/test_lhc_rdts.py
> +    the analytical model and MAD-NG. See
Yup

2025-01-10 11:03 UTC, jgray-19 commented on tests/inputs/lhc_rdts/create_data.py
> +# Convert a MAD-NG output into a fake measurement, then use OMC3 to calculate this fake measurement.
How about now?

2025-01-10 11:03 UTC, jgray-19 commented on tests/inputs/lhc_rdts/MAD_helpers.py
> +                        )
I've made some changes, what do you think?

2025-01-10 11:04 UTC, jgray-19 commented on tests/inputs/lhc_rdts/rdt_constants.py
> +    os.system(f"ln -s /afs/cern.ch/eng/acc-models/lhc/2024/ {ACC_MODELS}")
I see a lot of files do the hard link to the acc-models, since this is only for creating the data, is this ok?

2025-01-10 11:07 UTC, jgray-19 commented
> Upon double checking, I have no idea what the hell the `gh` tool is doing when checking out a PR. Here's what I can confirm:
> 
>     * git cloning the master branch (with `--depth=1`) -> 68.63 MiB downloaded.
> 
>     * git cloning directly your branch (with `--depth=1`) -> 73.61 MiB downloaded.
> 
> 
> My concern regarding this PR's file sizes is gone, since you're adding about 5MiB. Considering we are shipping 46M of binaries I guess there's only so much we can do. I dream of reworking things to use `cpymad` at some point, but never got around to it.

Ok. So the main causes of the increase in file size are the tracking data, in sdds format and the model folders. The model folders could be reduced, if we can compress the tfs files labelled .dat in there? But the sdds files, there a bit more difficult to reduce, as they're fairly well compressed. Perhaps the number of turns can be reduced, but this is undesirable for the test.

2025-01-10 12:51 UTC, JoschD commented on tests/inputs/lhc_rdts/omc3_helpers.py
> +def get_rdts_from_harpy(
not really the right name for this function, I think.
`get_rdts_from_optics_analysis` maybe?

2025-01-10 12:53 UTC, JoschD commented on tests/inputs/lhc_rdts/rdt_constants.py
> +
Why not `NORMAL_SEXTUPOLE_RDTS` etc?

2025-01-10 12:54 UTC, JoschD commented on tests/inputs/lhc_rdts/omc3_helpers.py
> +def get_rdts() -> list[str]:
`get_rdt_names()`

2025-01-10 12:54 UTC, JoschD commented on tests/inputs/lhc_rdts/rdt_constants.py
> +
and probably safer to make them tuples instead of lists.

2025-01-10 12:55 UTC, JoschD commented on tests/inputs/lhc_rdts/rdt_constants.py
> +from pathlib import Path
type-hints in this file missing

2025-01-10 13:00 UTC, JoschD commented on tests/accuracy/test_lhc_rdts.py
> +    rdt_dfs = get_rdts_from_harpy(beam, output_dir=analysis_path, check_previous=True)
to avoid re-running things, instead of the `check_previous` this could also be a fixture with scope="module"

2025-01-10 13:05 UTC, JoschD commented on tests/accuracy/test_lhc_rdts.py
> +    assert ng_diff.abs().max() < AMPLITUDE_TOLERANCES[beam][order]
why only `> 1`?

2025-01-10 13:06 UTC, jgray-19 commented on tests/accuracy/test_lhc_rdts.py
> +    assert np.allclose(omc_amplitude, omc_df["AMP"], rtol=1e-10)
Ok, yup. The aim is to check that the real, imag, amp and phase are all consistent, so will change the comment

2025-01-10 13:07 UTC, JoschD commented on tests/accuracy/test_lhc_rdts.py
> +    # Compare OMC3 phase to real and imaginary parts
# Check omc3 calculation of phase vs real and imaginary parts

2025-01-10 13:09 UTC, JoschD commented on tests/accuracy/test_lhc_rdts.py
> +    # Compare the phases
`# Compare omc3 vs MAD-NG phases`

2025-01-10 13:10 UTC, JoschD commented on tests/accuracy/test_lhc_rdts.py
> +        # Compare the amplitudes, relative when above 1, absolute when below
ah, that explains my question above. Maybe copy comment

2025-01-10 13:14 UTC, jgray-19 commented on tests/accuracy/test_lhc_rdts.py
> +        # Compare the phases (this for some reason fails for f1300_x, max diff of about 0.2)
I don't completely understand why the analytical calculation fails for some octupoles. I can show you some graphs to demonstrate my point. But it appears that there is some quadrupolar contribution that is not taken into account.

2025-01-10 13:24 UTC, jgray-19 commented on tests/inputs/lhc_rdts/rdt_constants.py
> +
Immutable?

2025-01-10 13:41 UTC, jgray-19 commented on tests/accuracy/test_lhc_rdts.py
> +    assert ng_diff.abs().max() < AMPLITUDE_TOLERANCES[beam][order]
Added comment

2025-01-10 13:41 UTC, jgray-19 commented on tests/accuracy/test_lhc_rdts.py
> +    if order == "sextupole":
Added comment, is that ok?

2025-01-10 13:48 UTC, JoschD commented on tests/accuracy/utils_lhc_rdts.py
> +    return NORMAL_SEXTUPOLE_RDTS + SKEW_SEXTUPOLE_RDTS + NORMAL_OCTUPOLE_RDTS + SKEW_OCTUPOLE_RDTS
I think this will now fail.

2025-01-10 15:33 UTC, fsoubelet commented on tests/accuracy/test_lhc_rdts.py
> +    run_harpy(beam=2)
That fixture seemed like it ran with all default values

2025-01-10 16:28 UTC, jgray-19 commented
> > Upon double checking, I have no idea what the hell the `gh` tool is doing when checking out a PR. Here's what I can confirm:
> > ```
> > * git cloning the master branch (with `--depth=1`) -> 68.63 MiB downloaded.
> > 
> > * git cloning directly your branch (with `--depth=1`) -> 73.61 MiB downloaded.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > My concern regarding this PR's file sizes is gone, since you're adding about 5MiB. Considering we are shipping 46M of binaries I guess there's only so much we can do. I dream of reworking things to use `cpymad` at some point, but never got around to it.
> 
> Ok. So the main causes of the increase in file size are the tracking data, in sdds format and the model folders. The model folders could be reduced, if we can compress the tfs files labelled .dat in there? But the sdds files, there a bit more difficult to reduce, as they're fairly well compressed. Perhaps the number of turns can be reduced, but this is undesirable for the test.

The most recent commit compresses the files. It reduces the files by 8 MB. This method could be extended to other tests, opinions?

2025-01-13 12:44 UTC, JoschD approved these changes

2025-01-13 13:27 UTC, jgray-19 commented
> Yes, thanks @jgray-19 ! I think, for the sake of this PR, let's stay in scope and leave compression of other test files to a different day.
> 
> Regarding the latest commit, is it necessary to compress then decompress the files with the fixture? They're just temporary files anyway for the duration of the test run, right? I think we should only care about the size of files we permanently store in the repo, not intermediate ones (and forgo the consumed time to do compression and decompression in the fixture).

No, it's not necessary. How about the new code?

2025-01-13 13:56 UTC, fsoubelet requested changes
This is just minor things now, very close to merge ;)

2025-01-13 13:56 UTC, fsoubelet commented on tests/utils/compression.py
> +        LOGGER.warning(f"File {read_path} does not exist. Cannot {'' if compress else 'de'}compress.")
I would like the function name and docstring to explicitely state we're talking about TFS files here.

2025-01-13 13:56 UTC, fsoubelet commented on tests/utils/compression.py
> +            file.unlink()
Could be
```python
file.unlink(missing_ok=True)
```

2025-01-13 13:56 UTC, fsoubelet commented on tests/utils/compression.py
> +    model_compression(model_dir, compress=False)
Not a fan of one-liners like this, I would rather have just two functions here, explicitely named. Maybe `compress_model_dir_files` and `decompress_model_dir_files`.

2025-01-13 14:09 UTC, JoschD commented on tests/inputs/lhc_rdts/model_b1/job.create_model_nominal.madx
> +}
I don't think there is a point of leaving these job.madx files here if you cannot run them anyway.
Also `create_data.py` does not exist.

2025-01-13 14:10 UTC, jgray-19 commented on tests/utils/compression.py
> +            file.unlink()
I think I would prefer to keep the warning

2025-01-13 14:10 UTC, jgray-19 commented on tests/utils/compression.py
> +    model_compression(model_dir, compress=False)
You mean, you would prefer the functions to not use model_compression? And just be separate functions?

2025-01-13 14:11 UTC, jgray-19 commented on tests/inputs/lhc_rdts/model_b1/job.create_model_nominal.madx
> +}
Ok yeah sure, I'll remove.

2025-01-13 14:48 UTC, jgray-19 commented on tests/utils/compression.py
> +    model_compression(model_dir, compress=False)
How about the most recent commit?

2025-01-13 14:51 UTC, fsoubelet commented on tests/utils/compression.py
> +            file.unlink()
Oh I had skipped that part somehow, sure.

2025-01-13 14:53 UTC, fsoubelet commented on tests/utils/compression.py
> +    model_compression(model_dir, compress=False)
Yeah sure, I didn't necessarily mean the removal of `file_compression` but that works, it's very little code duplication in a helper file anyway. Feel free to resolve.

2025-01-14 08:08 UTC, JoschD approved these changes

2025-01-14 08:30 UTC, fsoubelet approved these changes

2025-01-14 08:49 UTC, merged